version: '3.3'

services:

  nginx:
      container_name: nginx
      build: requirements/nginx
      hostname: localhost
      volumes:
          - wp:/var/www/wordpress
      networks:
          - app-network
      ports:
          - "443:443" #out networks only for nginx
      depends_on:
          - wordpress #dependance - nginx will launch after wordpress, nginx needs to send requests to wordpress, that's why we need to launch wordpress first
      restart: always #if container fails it will always relaunch

  mariadb:
      container_name: mariadb
      build: requirements/mariadb
      hostname: localhost
      volumes:
          - db:/var/lib/mysql
      environment: # we can connect env file, but we need only some of the vars, that's why we copy only them, it is more correct way
          DB_NAME: ${DB_NAME}
          DB_USER: ${DB_USER}
          DB_PASSWORD: ${DB_PASSWORD}
          DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      networkd:
          - app-network
      restart: always

  wordpress:
      container_name: wordpress
      build: requirements/wordpress
      hostname: localhost
      volumes:
          - wp:/var/www/wordpress
      environment:
          DB_HOST: ${DB_HOST}
          DB_NAME: ${DB_NAME}
          DB_USER: ${DB_USER}
          DB_PASSWORD: ${DB_PASSWORD}
          USER_NAME: ${USER_NAME
          USER_EMAIL: ${USER_EMAIL}
          USER_ADMIN_EMAIL: ${USER_ADMIN_EMAIL}
          DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
          DOMAIN_NAME: ${DOMAIN_NAME}
          TITLE: ${TITLE}
      networks:
          - app-network
      depends_on:
          - mariadb #dependance wordpress will launch after mariadb
      restart: always

volumes:
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: -/data/db #home directory where locally created the folder

    wp:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: -/data/wp

networks:
  app-network:
      driver: bridge


